// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SendARaven.Controllers.service;

namespace SendARaven.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20190725084822_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SendARaven.Models.TenantDetailsEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tenantId");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnName("apiKey")
                        .HasMaxLength(128);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnName("companyName")
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(128);

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnName("tenantName")
                        .HasMaxLength(128);

                    b.HasKey("TenantId");

                    b.ToTable("developer");
                });

            modelBuilder.Entity("SendARaven.Models.UserEntity", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userId");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnName("tenantId");

                    b.Property<string>("atr")
                        .IsRequired()
                        .HasColumnName("attributes");

                    b.HasKey("UserId");

                    b.ToTable("user1");
                });
#pragma warning restore 612, 618
        }
    }
}
