// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SendARaven.Controllers.service;

namespace SendARaven.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20190725192030_tablesupdated")]
    partial class tablesupdated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SendARaven.Models.ChannelEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnName("tenantId")
                        .HasMaxLength(128);

                    b.Property<string>("ChannelName")
                        .HasColumnName("channelName")
                        .HasMaxLength(128);

                    b.Property<int>("ChannelProvider")
                        .HasColumnName("channelProvider");

                    b.Property<int>("ChannelType")
                        .HasColumnName("channelType");

                    b.Property<int>("Status")
                        .HasColumnName("status");

                    b.Property<string>("TemplateId")
                        .HasColumnName("templateId")
                        .HasMaxLength(128);

                    b.Property<string>("chanconfig")
                        .HasColumnName("channelConfig");

                    b.HasKey("TenantId", "ChannelName");

                    b.ToTable("channel_entity");

                    b.HasData(
                        new
                        {
                            TenantId = "tenant_1",
                            ChannelName = "mail",
                            ChannelProvider = 0,
                            ChannelType = 1,
                            Status = 1,
                            TemplateId = "mail_sendgrid",
                            chanconfig = "{\"senderId\":\"test@example.com\",\"apiKey\":\"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\"}"
                        },
                        new
                        {
                            TenantId = "tenant_1",
                            ChannelName = "sms-t",
                            ChannelProvider = 1,
                            ChannelType = 0,
                            Status = 1,
                            TemplateId = "sms_msg91",
                            chanconfig = "{\"senderId\":\"TestId\",\"apiKey\":\"286355ArYeDDLx4EFP5d367ce1\"}"
                        });
                });

            modelBuilder.Entity("SendARaven.Models.TenantDetailsEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tenantId");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnName("apiKey")
                        .HasMaxLength(128);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnName("companyName")
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasMaxLength(128);

                    b.HasKey("TenantId");

                    b.ToTable("developer");

                    b.HasData(
                        new
                        {
                            TenantId = "tenant_1",
                            ApiKey = "key_1",
                            CompanyName = "Microsoft",
                            Email = "chaitanyachawla@yahoo.co.in"
                        });
                });

            modelBuilder.Entity("SendARaven.Models.UserChannelInformation", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnName("tenantId");

                    b.Property<string>("UserId")
                        .HasColumnName("userId");

                    b.Property<int>("ChannelType")
                        .HasColumnName("channelType");

                    b.Property<string>("UserChannelId")
                        .HasColumnName("userChannelId");

                    b.HasKey("TenantId", "UserId", "ChannelType");

                    b.ToTable("UserChannelInformations");

                    b.HasData(
                        new
                        {
                            TenantId = "tenant_1",
                            UserId = "user_1",
                            ChannelType = 1,
                            UserChannelId = "chaitanyachawla1996@gmail.com"
                        },
                        new
                        {
                            TenantId = "tenant_1",
                            UserId = "user_1",
                            ChannelType = 0,
                            UserChannelId = "9717795767"
                        },
                        new
                        {
                            TenantId = "tenant_1",
                            UserId = "user_2",
                            ChannelType = 1,
                            UserChannelId = "ashima.wadha.1996@gmail.com"
                        });
                });

            modelBuilder.Entity("SendARaven.Models.UserEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnName("tenantId");

                    b.Property<string>("UserId")
                        .HasColumnName("userId");

                    b.Property<string>("atr")
                        .IsRequired()
                        .HasColumnName("attributes");

                    b.HasKey("TenantId", "UserId");

                    b.ToTable("myuser");

                    b.HasData(
                        new
                        {
                            TenantId = "tenant_1",
                            UserId = "user_1",
                            atr = "{\"City\":\"Bangalore\"}"
                        },
                        new
                        {
                            TenantId = "tenant_1",
                            UserId = "user_2",
                            atr = "{\"City\":\"Bangalore\"}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
